name: Deploy

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - main
  workflow_dispatch:
# Jobs
jobs:
  Update:
    runs-on: self-hosted
    steps:
    - name: Deploy new code, install dependencies and start Advance
      run: ssh lemres@10.40.10.106 "cd ~/Advance && git pull && npm i && pm2 restart advance && pm2 save"